import pytest
from src.generator.data_generator import (
    generate_heart_rate,
    generate_heartbeat_event,
    event_stream,
    CUSTOMERS,
)
from src.config import (
    HEART_RATE_MIN_VALID,
    HEART_RATE_MAX_VALID,
    CUSTOMER_POOL_SIZE,
)


class TestGenerateHeartRate:
    """Tests for the heart rate generation function."""

    def test_normal_path_always_in_valid_range(self):
        """Run 1000 times — normal path must never produce anomalies."""
        for _ in range(1000):
            bpm = generate_heart_rate(inject_anomaly=False)
            assert HEART_RATE_MIN_VALID <= bpm <= HEART_RATE_MAX_VALID, (
                f"Normal path produced out-of-range BPM: {bpm}"
            )

    def test_anomaly_path_always_outside_valid_range(self):
        """Anomaly path must always produce values outside the valid range."""
        for _ in range(100):
            bpm = generate_heart_rate(inject_anomaly=True)
            assert bpm < HEART_RATE_MIN_VALID or bpm > HEART_RATE_MAX_VALID, (
                f"Anomaly path produced in-range BPM: {bpm}"
            )

    def test_anomaly_bradycardia_range(self):
        """Bradycardia anomalies must be below HEART_RATE_MIN_VALID."""
        bradycardia_values = []
        for _ in range(200):
            bpm = generate_heart_rate(inject_anomaly=True)
            if bpm < HEART_RATE_MIN_VALID:
                bradycardia_values.append(bpm)
        if bradycardia_values:
            assert all(15 <= bpm < HEART_RATE_MIN_VALID for bpm in bradycardia_values)

    def test_anomaly_tachycardia_range(self):
        """Tachycardia anomalies must be above HEART_RATE_MAX_VALID."""
        tachycardia_values = []
        for _ in range(200):
            bpm = generate_heart_rate(inject_anomaly=True)
            if bpm > HEART_RATE_MAX_VALID:
                tachycardia_values.append(bpm)
        if tachycardia_values:
            assert all(HEART_RATE_MAX_VALID < bpm <= 220 for bpm in tachycardia_values)

    def test_returns_integer(self):
        assert isinstance(generate_heart_rate(), int)
        assert isinstance(generate_heart_rate(inject_anomaly=True), int)


class TestGenerateHeartbeatEvent:
    """Tests for the event dict generated by the generator."""

    def test_event_has_required_fields(self):
        event = generate_heartbeat_event()
        assert "customer_id" in event
        assert "heart_rate" in event
        assert "timestamp" in event

    def test_customer_id_format(self):
        for _ in range(50):
            event = generate_heartbeat_event()
            assert event["customer_id"].startswith("CUST_"), (
                f"Unexpected customer_id format: {event['customer_id']}"
            )
            # CUST_XXXXX = 10 characters (5-digit zero-padded number)
            assert len(event["customer_id"]) == 10

    def test_customer_id_in_pool(self):
        for _ in range(50):
            event = generate_heartbeat_event()
            assert event["customer_id"] in CUSTOMERS

    def test_timestamp_is_string(self):
        event = generate_heartbeat_event()
        assert isinstance(event["timestamp"], str)

    def test_timestamp_contains_utc_offset(self):
        event = generate_heartbeat_event()
        # UTC ISO format includes +00:00
        assert "+00:00" in event["timestamp"] or "Z" in event["timestamp"]

    def test_heart_rate_is_integer(self):
        for _ in range(20):
            event = generate_heartbeat_event()
            assert isinstance(event["heart_rate"], int)


class TestCustomerPool:
    """Tests for the pre-generated customer pool."""

    def test_pool_size_matches_config(self):
        assert len(CUSTOMERS) == CUSTOMER_POOL_SIZE

    def test_all_customers_have_correct_format(self):
        for cid in CUSTOMERS:
            assert cid.startswith("CUST_")
            assert len(cid) == 10  # CUST_XXXXX — 5-digit zero-padded

    def test_customers_are_unique(self):
        assert len(CUSTOMERS) == len(set(CUSTOMERS))

    def test_first_customer(self):
        assert CUSTOMERS[0] == "CUST_00001"

    def test_last_customer(self):
        expected = f"CUST_{CUSTOMER_POOL_SIZE:05d}"
        assert CUSTOMERS[-1] == expected


class TestEventStream:
    """Tests for the generator function."""

    def test_finite_stream_yields_correct_count(self):
        events = list(event_stream(max_events=5))
        assert len(events) == 5

    def test_stream_yields_valid_event_dicts(self):
        for event in event_stream(max_events=3):
            assert isinstance(event, dict)
            assert "customer_id" in event
            assert "heart_rate" in event
            assert "timestamp" in event

    def test_stream_events_have_integer_heart_rates(self):
        for event in event_stream(max_events=10):
            assert isinstance(event["heart_rate"], int)
